baseURL = "https://sgoodliff.github.io/"
languageCode = "en-us"
title = "My Infrequent Thoughts"
theme = "minimo"

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]
footer = ["social_menu"]

[params.social]
email = "contact@example.com"
github = "sgoodliff"
linkedin = "steven-goodliff-968806122"
twitter = "roadwarrior78"
youtube = "UCED7j7x7HqvvWrUJUTOOYgw"
